version: "3.8"

services:
  learn_oauth_db:
    image: postgres:latest
    container_name: learn_oauth_db
    ports:
      - ${DB_HOST_PORT}:${DB_DOCKER_PORT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - learn_oauth_volumes:/var/lib/postgresql/data
    networks:
      - learn_oauth_network

volumes:
  learn_oauth_volumes:
    name: "learn_oauth_volumes"

networks:
  learn_oauth_network:
    name: "learn_oauth_network"
    driver: "bridge"
